Added new number separator.
danbettles/telex pull request #1
Opened 2018-07-06 11:53 UTC by adumitrache

2018-07-06 14:15 UTC, danbettles requested changes

2018-07-06 14:15 UTC, danbettles commented on tests/DanBettles/Telex/TelexTest/telephone_numbers.csv
> +1,+33 693+633333
Could you add a couple more tests to see what now happens when you have a case like `+33 693+633333/+33 789 456123`, please?  Thanks.

2018-07-06 14:24 UTC, adumitrache commented on tests/DanBettles/Telex/TelexTest/telephone_numbers.csv
> +1,+33 693+633333
@danbettles Done :smiley:

2018-07-09 09:37 UTC, danbettles commented
Thanks, Adrian

2018-07-09 09:37 UTC, merged